### ISSUE TITLE
Watcher and Star result same value 

### ISSUE THREAD

**Issue by acbarbosa1964** [mdo/github-buttons#103]
Dear friend,

https://ghbtns.com/github-btn.html?user=acbarbosa1964&repo=acb-bootstrap-snippets&type=watch&count=true (results 53 should be 12)

and 

https://ghbtns.com/github-btn.html?user=acbarbosa1964&repo=acb-bootstrap-snippets&type=star&count=true (is 53 - correct)

Both result same result.

Best regards,

**Comment by benjycui** [comment]
GitHub API's issue. The same in https://github.com/benjycui/react-github-button/
