### ISSUE TITLE
Issues button?

### ISSUE THREAD

**Issue by alexylem** [mdo/github-buttons#108]
https://buttons.github.io
Provides an "Issues" button previewing nb of open issues:
![image](https://cloud.githubusercontent.com/assets/11017174/19731105/9cb3396a-9b9c-11e6-87cc-816a64f38cb9.png)
Is it possible to have it at ghbtns.com?
Thanks!

**Comment by mdo** [comment]
Been a long time since I looked at this, but no plans for adding this myself.
