### ISSUE TITLE
Does not support/follow username changes

### ISSUE THREAD

**Issue by ahmetb** [mdo/github-buttons#110]
I just changed my username from `ahmetalpbalkan` to `ahmetb`. Normally github handles redirections well. However gbtns apparently doesnt.

The iframe stops showing star data, it gets this response:

![image](https://cloud.githubusercontent.com/assets/159209/23327359/66acf16c-fabf-11e6-9b41-e81e41b2ac26.png)

Example: https://ghbtns.com/github-btn.html?user=ahmetalpbalkan&repo=go-dexec&type=star&count=true&size=large
Repo: https://github.com/ahmetalpbalkan/go-dexec
..redirects to: https://github.com/ahmetb/go-dexec

**Comment by mdo** [comment]
This repo is part of GitHub, this needs to be updated by you.
