### ISSUE TITLE
URL not valid in iframe

### ISSUE THREAD

**Issue by bsoyka** [mdo/github-buttons#116]
I am trying to use the star button in a GitHub Pages website, and the & signs in the URL have been highlighted red in the index.html file.  Am I doing something wrong?

**Comment by bsoyka** [comment]
I have just realized that the button still works, but the `&`s are still highlighted in red.

**Comment by mdo** [comment]
You can leave them as-is—should be fine :). Sometimes you need to use the unicode instead though—`&amp;`.
