### ISSUE TITLE
Add icon-only variant

### ISSUE THREAD

**Issue by mdo** [mdo/github-buttons#141]
Wonder if it'd make sense to do an icon-only version where there is no button text?

**Comment by XhmikosR** [comment]
Isn't this what you mean?

```
https://ghbtns.com/github-btn.html
```

**Comment by XhmikosR** [comment]
@mdo can you try https://github.com/mdo/github-buttons/tree/no-text?

BTW I'm open to suggestions about the parameter name, the CSS and everything.

**Comment by Er2422110** [comment]
https://github.com/mdo/github-buttons/issues/159

**Comment by Er2422110** [comment]
https://github.com/mdo/github-buttons/issues/159
