### ISSUE TITLE
The star counter is not working anymore

### ISSUE THREAD

**Issue by trolologuy** [mdo/github-buttons#153]
Hello

The [star counter](https://ghbtns.com/#star) seems to not be working anymore.
It's creating the following messages in the console:
`The resource from “https://api.github.com/repos/trolologuy/useful-tools?callback=callback” was blocked due to MIME type (“application/json”) mismatch (X-Content-Type-Options: nosniff).
github-btn.html
Loading failed for the <script> with source “https://api.github.com/repos/trolologuy/useful-tools?callback=callback”.`

[Example](https://ghbtns.com/github-btn.html?user=trolologuy&repo=useful-tools&type=star&count=true&size=small)

**Comment by mdo** [comment]
Shows up fine for me.

**Comment by trolologuy** [comment]
Indeed after checking again this morning everything seems fine again. It was probably a short bug, apologies for the false alert.

**Comment by XhmikosR** [comment]
It's a common issue when one hits the GitHub API rate limit. A PR to document this is welcome.
