### ISSUE TITLE
Star count no longer showing on one of my GitHub buttons

### ISSUE THREAD

**Issue by klyburke** [mdo/github-buttons#162]
Thank you for creating and open sourcing github-buttons! We've used them on our website for 2+ years now.

We recently noticed that one of our buttons no longer displays the star count; however, the second button is working just fine.

Here are links to the buttons:
working: https://ghbtns.com/github-btn.html?user=async-labs&repo=saas&type=star&count=true&size=large
not working: https://ghbtns.com/github-btn.html?user=builderbook&repo=builderbook&type=star&count=true&size=large

Do you know what the problem could be?

**Comment by XhmikosR** [comment]
Both seem to work fine.

My guess is you hit the GitHub API rate limit thus for ~1 hour you won't see any buttons. We should probably document this somewhere.

**Comment by XhmikosR** [comment]
Closing for the aforementioned reason. If you want, you can submit a PR to document this behavior. IIRC the unauthenticated rate limit is 60 requests per hour.

**Comment by klyburke** [comment]
@XhmikosR thanks for the reply and information.

Are you able to see the star count for this button? https://ghbtns.com/github-btn.html?user=builderbook&repo=builderbook&type=star&count=true&size=large

I still don't see anything, and it has not been showing for a few weeks now. I'm not sure that we've just hit a limit and need to wait an hour. To me, it seems there is a different problem.

**Comment by XhmikosR** [comment]
I was seeing and still seeing the star count here:

![Untitled](https://user-images.githubusercontent.com/349621/93637325-15255900-f9fe-11ea-99c7-84f097c3c2ad.png)

Not sure why you are having this issue apart from rate limiting which you shouldn't really hit. How about trying in an incognito window and/or on a different network?

**Comment by klyburke** [comment]
@XhmikosR Thanks for sharing the screenshot and suggestions. I'm still not seeing the number on my computer/phone in incognito or on a different network. I'll have to keep investigating.
