### ISSUE TITLE
Two :star: buttons with a displayed count for different repositories on the same page display count of first repository that loads

### ISSUE THREAD

**Issue by ctrlcctrlv** [mdo/github-buttons#175]
![image](https://user-images.githubusercontent.com/838783/132778703-3fb88306-6a3c-42bf-a776-5484bc4f09cc.png)
![image](https://user-images.githubusercontent.com/838783/132778858-eabf39f0-0e26-4cfd-9233-f856db5d2aae.png)

**Comment by XhmikosR** [comment]
Please share a Codepen, screenshots are pretty much useless.

**Comment by ctrlcctrlv** [comment]
@XhmikosR Does 4.0.15 fix this?

**Comment by XhmikosR** [comment]
No, I asked you for a CodePen and you didn't provide one...
