### ISSUE TITLE
javascript version (doesn't use iframes)

### ISSUE THREAD

**Issue by jonathanong** [mdo/github-buttons#51]
i made a javascript version: https://github.com/jonathanong/github-buttons

however, i don't want to maintain this. anyone want to maintain it? host it on a CDN? etc? replace this repo with it?

**Comment by bsoyka** [comment]
Done.
[CSS](https://cdn.rawgit.com/component/github-buttons/45e6a194/dist/github-buttons.css)
[JS](https://cdn.rawgit.com/component/github-buttons/45e6a194/dist/github-buttons.js)
These are permanent copies of what the files are now, but they are easy to update at [RawGit.com](https://rawgit.com)
