### ISSUE TITLE
SSL and free certificates for ghbtns.com

### ISSUE THREAD

**Issue by EHLOVader** [mdo/github-buttons#73]
I know you have addressed SSL in the readme, and beyond selfhosting could you offer SSL on your domain using a free SSL solution like https://www.startssl.com/ ?

I think it would be helpful others as I continue to run into gh-pages where not just your buttons but all of the resources have been included with explicit HTTP protocol and fail to work. This is made more complicated by the use of extensions like https everywhere which treat github as a secure only site.

**Comment by EHLOVader** [comment]
+1 for cloudflare's universal SSL solution @Jaex mentioned.

**Comment by PeterDaveHello** [comment]
+1

**Comment by mdo** [comment]
Added the CloudFlare SSL support this weekend—happy `https://`-ing!

**Comment by mchelen** [comment]
@mdo That's great to see, thanks!
