### ISSUE TITLE
http can't access http

### ISSUE THREAD

**Issue by jasonshark** [mdo/github-buttons#77]
I'm getting a strange protocol must match error. 

`Uncaught SecurityError: Blocked a frame with origin "http://ghbtns.com" from accessing a frame with origin "http://localhost:3000". Protocols, domains, and ports must match. `

This is my iframe code:
```
<iframe src="http://ghbtns.com/github-btn.html?user=jasonshark&repo=oakland-crime-api&type=fork&count=true" allowtransparency="true" frameborder="0" scrolling="0" width="62" height="20"></iframe>
```

How can http not match http? I am running a node.js express server. I'm hoping this isn't a [chrome issue](http://stackoverflow.com/questions/17876656/youtube-blocked-a-frame-with-origin-http-www-youtube-com-from-accessing-a-f). Anyone else run into this?

**Comment by mdo** [comment]
Not sure if this ever was resolved, but it may have been caused by some downtime or if you were indeed using a local server (there are security concerns with cross site iframes). Closing out for now, but holler if there's still a problem.
