### ISSUE TITLE
Show a warning for IE < 9 for the website

### ISSUE THREAD

**Issue by XhmikosR** [mdo/github-buttons#80]
...since things don't work nice with IE < 9.

**Comment by XhmikosR** [comment]
Actually, it's easy to fix, by using https://github.com/chuckcarpenter/REM-unit-polyfill

Also, adding a PNG fallback for the ico is just 700 bytes more.

Let me know what you think.

**Comment by XhmikosR** [comment]
...but I guess will hit the issue with `background-size` anyway...

**Comment by XhmikosR** [comment]
I think it might be better (it's definitely easier) if we just dropped support for pre IE 9 at this point.

**Comment by mdo** [comment]
I can mention browser support in the docs.

**Comment by XhmikosR** [comment]
We can just add a conditional for Internet Explorer less than 9 for
starters.

**Comment by mdo** [comment]
Closing as stale.
