### ISSUE TITLE
HTML validation errors

### ISSUE THREAD

**Issue by szepeviktor** [mdo/github-buttons#91]
Please change `width="160px"` to `width="160"` in `<iframe>`.
Please display `&amp;repo=bootstrap` instead of `&repo=bootstrap`.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fghbtns.com%2F
Please consider not suggesting non-HTML5 iframe attributes.

Thank you!

**Comment by ahtee** [comment]
I dont see any px in the actual code (index.md), not sure how it was added when brought togther and displayed on the page..

**Comment by szepeviktor** [comment]
Could it be Jekyll?

**Comment by XhmikosR** [comment]
It's just the gh-page branch is behind master I think.

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/80141704-43ffe600-85aa-11ea-9601-30b3bc6717f8.png)


2020-04-23

**Comment by XhmikosR** [comment]
It's fixed in master, it'll be pushed soon.

**Comment by XhmikosR** [comment]
https://mdo-8674181fab.drafts.github.io/github-buttons/

**Comment by szepeviktor** [comment]
Thank you.

Almost there! Ampersands need to be encoded.

**Comment by XhmikosR** [comment]
Nah, the ampersands are fine, we use utf-8: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmdo-8674181fab.drafts.github.io%2Fgithub-buttons%2F
