### ISSUE TITLE
X-Frame-Options set to DENY

### ISSUE THREAD

**Issue by mholt** [mdo/github-buttons#96]
I am currently experiencing this on your site as well as my own:

<img width="1436" alt="screen shot 2016-01-12 at 7 02 23 pm" src="https://cloud.githubusercontent.com/assets/1128849/12282884/0f296698-b95f-11e5-9f1f-274a7138f5a0.png">

This seems new. Like, even as of a few hours ago. Here's a glimpse at the response headers:

<img width="401" alt="screen shot 2016-01-12 at 7 03 24 pm" src="https://cloud.githubusercontent.com/assets/1128849/12282899/2f2ee2f6-b95f-11e5-854f-c83ce6560c7d.png">

What is adding that header and is there a way to change/remove it so it works again? :smile:

**Comment by mdo** [comment]
I imagine something has changed on GitHub Pages. I'll poke around and see what I can find out.

**Comment by jondubois** [comment]
Same here.

**Comment by mdo** [comment]
There was a security change that has since been rolled back. Unclear if it'll happen again, but I'll holler if I find out more info.
